### ISSUE TITLE
Error While Running transcription = stt.transcribe("audio.wav")

### ISSUE THREAD

**Issue by nayeem01** [shhossain/BanglaSpeech2Text#36]
ValueError: You are trying to return timestamps, but the generation config is not properly set. Make sure to initialize the generation config with the correct attributes that are needed such as `no_timestamps_token_id`. For more details on how to generate the approtiate config

**Comment by shhossain** [comment]
@nayeem01 Can you reproduce the error? If so, how?

**Comment by nayeem01** [comment]
![Screenshot 2024-10-19 090858](https://github.com/user-attachments/assets/408f9017-196d-4bc3-96d1-ed266a7ef98a)

**Comment by nayeem01** [comment]
@shhossain Whenever I try to run normally, it fails.

**Comment by shhossain** [comment]
@nayeem01 downgrade transformers version for now. i will try to solve it when i get time.

**Comment by aaqif-elo** [comment]
Same issue as @nayeem01 

Repro:

=> New python project (venv with Python 3.10.11)
=> pip install banglaspeech2text

```
from banglaspeech2text import Speech2Text
stt = Speech2Text()
transcript = stt.recognize(path_to_audio_file)
```

The error message directed here:

https://github.com/huggingface/transformers/issues/21878#issuecomment-1451902363

Full Traceback:

Traceback (most recent call last):
  File "project\cli.py", line 41, in <module>
    transcript_file_path = transcribe.transcribe(audio_path)
  File "project\transcribe.py", line 70, in transcribe
    transcript = stt.recognize(temp_file_path)
  File "project\.venv\lib\site-packages\banglaspeech2text\speech2text.py", line 451, in recognize
    return self.pipeline(data, *args, **kw)["text"]  # type: ignore
  File "project\.venv\lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 283, in __call__
    return super().__call__(inputs, **kwargs)
  File "project\.venv\lib\site-packages\transformers\pipelines\base.py", line 1294, in __call__
    return next(
  File "project\.venv\lib\site-packages\transformers\pipelines\pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "project\.venv\lib\site-packages\transformers\pipelines\pt_utils.py", line 269, in __next__
    processed = self.infer(next(self.iterator), **self.params)
  File "project\.venv\lib\site-packages\transformers\pipelines\base.py", line 1209, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "project\.venv\lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 515, in _forward
    tokens = self.model.generate(
  File "project\.venv\lib\site-packages\transformers\models\whisper\generation_whisper.py", line 533, in generate
    timestamp_begin = self._set_return_timestamps(
  File "project\.venv\lib\site-packages\transformers\models\whisper\generation_whisper.py", line 1216, in _set_return_timestamps
    raise ValueError(
ValueError: You are trying to return timestamps, but the generation config is not properly set. Make sure to initialize the generation config with the correct attributes that are needed such as `no_timestamps_token_id`. For more details on how to generate the approtiate config, refer to https://github.com/huggingface/transformers/issues/21878#issuecomment-1451902363

**Comment by shhossain** [comment]
@nayeem01 @aaqif-elo Apologies for the delay; I've been busy. I’ll look into the issue and get it fixed today.

**Comment by shhossain** [comment]
@nayeem01 @aaqif-elo update to latest version and check if problem presists.
```bash
pip install BanglaSpeech2Text==1.0.9
```

**Comment by aaqif-elo** [comment]
Unfortunately, the issue seems to still be there. 

I have updated to v1.0.9 and I can see the config added to speech2text.py

```python
# set generation config
            generation_config_model = get_generation_model(self.raw_name)
            try:
                gen_config = transformers.GenerationConfig.from_pretrained(
                    generation_config_model
                )
                self.pipeline.model.generation_config = gen_config
            except Exception as e:
                pass
```

But I'm still getting the error 

`ValueError: You are trying to return timestamps, but the generation config is not properly set. Make sure to initialize the generation config with the correct attributes that are needed such as `no_timestamps_token_id`. For more details on how to generate the approtiate config, refer to https://github.com/huggingface/transformers/issues/21878#issuecomment-1451902363`

**Comment by shhossain** [comment]
@aaqif-elo which model are you using?

**Comment by aaqif-elo** [comment]
```python
stt = Speech2Text()
```

I did not define a model so I am assuming it defaults to `base`

```python
model: str = "base",
```

**Comment by Mushfiq2002** [comment]
Hello,
Did the issue got fixed?Cz it does not seems so from my end

**Comment by shhossain** [comment]
@Mushfiq2002 @nayeem01 @aaqif-elo  The code was quite old, and many things were not working. I had planned to rewrite the entire codebase for a while but never had the time. Finally, I got the chance and implemented it. It now also supports timestamps. You can check the updated README for more details.

Sorry for the long delay, but your issues should be resolved now.

Update the package with:
```bash
pip install BanglaSpeech2Text -U
```
